# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    env_file:
      - '../.env'
    image: docker.io/bitnami/mariadb:11.4
    # container_name: server-mariadb-1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - '.moodle/mariadb:/bitnami/mariadb'
    ports:
      - '3306:3306'
  
  moodle:
    env_file:
      - '../.env'
    image: docker.io/bitnami/moodle:${MOODLE_VERSION}
    # container_name: server-moodle-1
    ports:
      - '${HTTP_PORT}:8080'
      - '${HTTPS_PORT}:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=admin
      - BITNAMI_DEBUG=true
    volumes:
      - '.moodle/moodle:/bitnami/moodle'
      - '.moodle/moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb